version: 

services: #つくりたいコンテナたちを記述する
  mariadb:
    image: mariadb
    volumes: 
    restart: always
    environment:
      - name=value
    depends_on:
      - serviceName
    ports: 
    entrypoint:
    build:
      context: buildContext
      dockerfile:
      args:
    env_file:
    networks:
  
  nginx:
    image: nginx
    volumes: 
    restart: always
    environment:
      - name=value
    depends_on:
    ports: 443:443 # Containerの外とつなぐポート（WWWにつなぐポート）
    entrypoint:
    build: ./requirements/nginx
      context: 
      dockerfile:
      args:
    env_file:
    networks:

  wordpress:
    image: 
    volumes: 
    restart: always
    environment:
      - name=value
    depends_on:
      - serviceName
    ports:
    entrypoint:
    build:
      context: buildContext
      dockerfile:
      args:
    env_file:
    networks: