services:
  #mariadb
  mariadb:
    restart: always
    image: mariadb
    container_name: mariadb
    init: true
    build:
      context: requirements/mariadb/.
      args:
        - {DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_RACINE=${DB_RACINE}
        - DB_RPASS=${DB_RPASS}
    ports: 
      - 3306:3306
    networks:
      - 42network
    volumes:
      - db_volume:/

  #wordpress
  wordpress:
    depends_on:
      - mariadb
    restart: always
    image: wordpress
    container_name: wordpress
    init: true
    build:
      environment:
        - WP_ADMIN=${WP_ADMIN}
        - WP_APASS=${WP_APASS}
        - WP_AMAIL=${WP_AMAIL}
        - WP_USER=${WP_USER}
        - WP_PASS=${WP_PASS}
        - WP_MAIL=${WP_MAIL}
        - WP_TITLE=${WP_TITLE}
        - WP_URL=${WP_URL}
    ports:
      - 9000:9000
    networks:
      - 42network
    volumes:
      - wp_volumes:/

  # nginx
  nginx:
    depends_on:
      - wordpress
    restart: always
    image: nginx
    container_name: nginx
    init: true
    build: requirements/nginx/.
    ports:
      - 443:443
    networks:
      - 42network
    volumes:
      - wp_volumes:/var/www/html/

volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      device: ${BUILD_PATH}wp
      o: bind
      type: none

  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      device: ${BUILD_PATH}db
      o: bind
      type: none
