# version: '3.7'

services:
  nginx:
    image: nginx
    restart: on-failure
    container_name: nginx
    init: true
    build:
      context: requirements/nginx/.
    volumes: 
      - wp_volume:/var/www/html/
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    networks:
      - 42network

  mariadb:
    image: mariadb
    restart: on-failure
    container_name: mariadb
    init: true
    build:
      context: requirements/mariadb/.
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_RACINE=${DB_RACINE}
        - DB_RPASS=${DB_RPASS}
    networks:
      - 42network
    volumes:
      - db_volume:/var/lib/mysql/
  
  wordpress:
    image: wordpress
    container_name: wordpress
    init: true
    volumes:
      - wp_volume:/var/www/html/
    restart: on-failure
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/.
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_RACINE=${DB_RACINE}
        - DB_HOST=${DB_HOST}
    environment:
      - WP_ADMIN=${WP_ADMIN}
      - WP_APASS=${WP_APASS}
      - WP_AMAIL=${WP_AMAIL}
      - WP_USER=${WP_USER}
      - WP_PASS=${WP_APASS}
      - WP_MAIL=${WP_MAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
    networks:
      - 42network

volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      device: /home/selee/data/wp_volume
      o: bind
      type: none
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      device: /home/selee/data/db_volume
      o: bind
      type: none

networks:
  42network:
    name: 42network
    driver: bridge
